Update license and enhance Spark configuration: - Changed license to Creative Commons Attribution-NonCommercial 4.0 International. - Improved run.sh to ensure no stale processes before starting the application. - Updated SparkConfig for better local mode handling and resource settings. - Enhanced AdEventSparkStreamer with improved logging and batch processing. - Adjusted logging configurations in application.properties and log4j2.xml for better performance.

diff --git a/root/docker/docker-compose.yml b/root/docker/docker-compose.yml
--- a/root/docker/docker-compose.yml
+++ b/root/docker/docker-compose.yml
@@ -156,86 +156,86 @@ services:
     networks:
       - docker_bi_network
 
-  # ================== AIRFLOW SERVICES ==================
-  # --► Airflow for orchestration
-  airflow-init:
-    <<: *airflow-common
-    container_name: tabularasa_airflow_init
-    entrypoint: /bin/bash
-    command:
-      - -c
-      - |
-        if [[ -z "$${AIRFLOW_UID}" ]]; then
-          echo;
-          echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m";
-          echo "If you are on Linux, you SHOULD follow the instructions below to set ";
-          echo "AIRFLOW_UID environment variable, otherwise files will be owned by root.";
-          echo "For other operating systems you can get rid of the warning with manually created .env file:";
-          echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user";
-          echo;
-        fi;
-        one_meg=1048576;
-        mem_available=$(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / one_meg));
-        cpus_available=$(grep -cE 'cpu[0-9]+' /proc/stat);
-        disk_available=$(df / | tail -1 | awk '{print $$4}');
-        warning_resources="false";
-        if (( mem_available < 2000 )) ; then
-          echo;
-          echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker (Recommend >2GB).\e[0m";
-          echo "You have $(numfmt --to iec $((mem_available * one_meg)))";
-          warning_resources="true";
-        fi;
-        if (( cpus_available < 1 )); then
-          echo;
-          echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker (Recommend >1).\e[0m";
-          echo "You have $${cpus_available}";
-          warning_resources="true";
-        fi;
-        if [[ $${warning_resources} == "true" ]]; then
-          echo;
-          echo -e "\033[1;33mWARNING!!!: You might have not enough resources for a smooth Airflow experience!\e[0m";
-          echo;
-        fi;
-        airflow db init && \
-        airflow users create \
-          --username ${AIRFLOW_WWW_USER_USERNAME:-admin} \
-          --firstname ${AIRFLOW_WWW_USER_FIRSTNAME:-Admin} \
-          --lastname ${AIRFLOW_WWW_USER_LASTNAME:-User} \
-          --role ${AIRFLOW_WWW_USER_ROLE:-Admin} \
-          --email ${AIRFLOW_WWW_USER_EMAIL:-admin@example.com} \
-          --password ${AIRFLOW_WWW_USER_PASSWORD:-admin}
+  # # ================== AIRFLOW SERVICES ==================
+  # # --► Airflow for orchestration
+  # airflow-init:
+  #   <<: *airflow-common
+  #   container_name: tabularasa_airflow_init
+  #   entrypoint: /bin/bash
+  #   command:
+  #     - -c
+  #     - |
+  #       if [[ -z "$${AIRFLOW_UID}" ]]; then
+  #         echo;
+  #         echo -e "\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m";
+  #         echo "If you are on Linux, you SHOULD follow the instructions below to set ";
+  #         echo "AIRFLOW_UID environment variable, otherwise files will be owned by root.";
+  #         echo "For other operating systems you can get rid of the warning with manually created .env file:";
+  #         echo "    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user";
+  #         echo;
+  #       fi;
+  #       one_meg=1048576;
+  #       mem_available=$(($(getconf _PHYS_PAGES) * $(getconf PAGE_SIZE) / one_meg));
+  #       cpus_available=$(grep -cE 'cpu[0-9]+' /proc/stat);
+  #       disk_available=$(df / | tail -1 | awk '{print $$4}');
+  #       warning_resources="false";
+  #       if (( mem_available < 2000 )) ; then
+  #         echo;
+  #         echo -e "\033[1;33mWARNING!!!: Not enough memory available for Docker (Recommend >2GB).\e[0m";
+  #         echo "You have $(numfmt --to iec $((mem_available * one_meg)))";
+  #         warning_resources="true";
+  #       fi;
+  #       if (( cpus_available < 1 )); then
+  #         echo;
+  #         echo -e "\033[1;33mWARNING!!!: Not enough CPUS available for Docker (Recommend >1).\e[0m";
+  #         echo "You have $${cpus_available}";
+  #         warning_resources="true";
+  #       fi;
+  #       if [[ $${warning_resources} == "true" ]]; then
+  #         echo;
+  #         echo -e "\033[1;33mWARNING!!!: You might have not enough resources for a smooth Airflow experience!\e[0m";
+  #         echo;
+  #       fi;
+  #       airflow db init && \
+  #       airflow users create \
+  #         --username ${AIRFLOW_WWW_USER_USERNAME:-admin} \
+  #         --firstname ${AIRFLOW_WWW_USER_FIRSTNAME:-Admin} \
+  #         --lastname ${AIRFLOW_WWW_USER_LASTNAME:-User} \
+  #         --role ${AIRFLOW_WWW_USER_ROLE:-Admin} \
+  #         --email ${AIRFLOW_WWW_USER_EMAIL:-admin@example.com} \
+  #         --password ${AIRFLOW_WWW_USER_PASSWORD:-admin}
   
-  airflow-webserver:
-    <<: *airflow-common
-    container_name: tabularasa_airflow_webserver
-    command: webserver
-    ports:
-      - "8080:8080"
-    healthcheck:
-      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
-      interval: 30s
-      timeout: 10s
-      retries: 5
-      start_period: 30s
-    restart: always
-    depends_on:
-      airflow-init:
-        condition: service_completed_successfully
+  # airflow-webserver:
+  #   <<: *airflow-common
+  #   container_name: tabularasa_airflow_webserver
+  #   command: webserver
+  #   ports:
+  #     - "8080:8080"
+  #   healthcheck:
+  #     test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+  #     interval: 30s
+  #     timeout: 10s
+  #     retries: 5
+  #     start_period: 30s
+  #   restart: always
+  #   depends_on:
+  #     airflow-init:
+  #       condition: service_completed_successfully
 
-  airflow-scheduler:
-    <<: *airflow-common
-    container_name: tabularasa_airflow_scheduler
-    command: scheduler
-    healthcheck:
-      test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --limit 1 | grep -c 'SUCCESS' || exit 1"]
-      interval: 30s
-      timeout: 20s
-      retries: 5
-      start_period: 30s
-    restart: always
-    depends_on:
-      airflow-init:
-        condition: service_completed_successfully
+  # airflow-scheduler:
+  #   <<: *airflow-common
+  #   container_name: tabularasa_airflow_scheduler
+  #   command: scheduler
+  #   healthcheck:
+  #     test: ["CMD-SHELL", "airflow jobs check --job-type SchedulerJob --limit 1 | grep -c 'SUCCESS' || exit 1"]
+  #     interval: 30s
+  #     timeout: 20s
+  #     retries: 5
+  #     start_period: 30s
+  #   restart: always
+  #   depends_on:
+  #     airflow-init:
+  #       condition: service_completed_successfully
 
   # ================== MONITORING STACK ==================
   # --► Prometheus, Grafana, Jaeger for observability
